# Generated by Django 4.1.7 on 2023-06-29 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_communityboard_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="작성 일시"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="communityboard",
            name="category",
            field=models.CharField(
                choices=[
                    ("정보공유", "정보공유"),
                    ("소통해요", "소통해요"),
                    ("칭찬해요", "칭찬해요"),
                    ("나눔해요", "나눔해요"),
                ],
                default="정보공유",
                max_length=10,
                verbose_name="게시판 카테고리",
            ),
        ),
        migrations.AlterField(
            model_name="complainboard",
            name="content",
            field=models.TextField(verbose_name="민원 내용"),
        ),
        migrations.AlterField(
            model_name="complainboard",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="작성 일시"
            ),
        ),
        migrations.AlterField(
            model_name="complainboard",
            name="title",
            field=models.CharField(max_length=200, verbose_name="민원 제목"),
        ),
        migrations.AlterField(
            model_name="reply",
            name="content",
            field=models.TextField(verbose_name="댓글 내용"),
        ),
        migrations.AlterField(
            model_name="reply",
            name="created_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="작성 일시"
            ),
        ),
        migrations.AlterField(
            model_name="sound_level_verified",
            name="sound_type",
            field=models.CharField(
                choices=[
                    ("발걸음소리", "발걸음소리"),
                    ("가구끄는소리", "가구끄는소리"),
                    ("악기소리", "악기소리"),
                    ("동물소리", "동물소리"),
                ],
                default="발걸음소리",
                max_length=30,
                verbose_name="소음 종류",
            ),
        ),
    ]
