# Generated by Django 4.1.7 on 2023-07-04 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_noticeboard_alter_communityboard_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound_level_verified',
            name='sound_type',
            field=models.CharField(choices=[('충격음', '충격음'), ('가구끄는소리', '가구끄는소리'), ('진공청소기', '진공청소기'), ('악기소리', '악기소리'), ('반려동물', '반려동물')], default='발걸음소리', max_length=30, verbose_name='소음 종류'),
        ),
        migrations.CreateModel(
            name='ComplainBoardReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변 내용')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성 일시')),
                ('author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('complain_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.complainboard')),
            ],
        ),
    ]
